apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  type: NodePort
  selector:
    app: dashboard # Routes traffic to ANY pod with this label
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080 # This exposes the app to your host machine